version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fpdb
      - POSTGRES_HOST=db
    expose:
      - 5432
  redis:
    image: redis
  web:
    build: .
    restart: always
    ports:
     - "5000:5000"
    volumes:
     - data-volume:/api/instance
    command: ["./start.sh"]
    depends_on:
      - db
      - redis
  worker:
    build:
      context: .
      dockerfile: ./celery-queue/Dockerfile
    restart: always
    volumes:
      - data-volume:/api/instance
    depends_on:
      - redis
  beat:
    build:
      context: .
    container_name: beat
    entrypoint: celery
    command: -A app.celery beat --loglevel=info
    volumes:
      - .:/var/www/app/beat
    links:
      - worker
      - redis
    depends_on:
      - worker
      - redis
volumes:
  data-volume: