"""empty message

Revision ID: 189df152c967
Revises: 
Create Date: 2021-02-08 20:46:51.159293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189df152c967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ytsearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.String(length=24), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ytsearch')
    # ### end Alembic commands ###
