"""empty message

Revision ID: 3f42febe4158
Revises: 189df152c967
Create Date: 2021-02-09 18:41:20.253742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f42febe4158'
down_revision = '189df152c967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ytsearch', sa.Column('channel_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ytsearch', 'channel_title')
    # ### end Alembic commands ###
